name = "openapisearch"
main = "main.ts"
dev.port = 3000
compatibility_date = "2025-03-13"
assets.directory = "./"
routes = [
  { pattern = "openapisearch.com", custom_domain = true },
  { pattern = "www.openapisearch.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "OPENAPI_LOCATIONS"
id = "2e7b10d8ab164f77baf32e9a40f1357c"